volumes:
  rabbitmq_data: {}

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672" # RabbitMQ Management UI
      - "5672:5672" # RabbitMQ AMQP protocol
    env_file:
      - .env
    environment:
      - RABBITMQ_LOAD_DEFINITIONS: /etc/rabbitmq/definitions.json
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    external: true
