volumes:
  rabbitmq_data: {}

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672" # RabbitMQ Management UI
      - "5672:5672" # RabbitMQ AMQP protocol
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq:/config
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rabbitmq_net
      - default
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_management load_definitions \"/config/definitions.json\""



networks:
  default:
    driver: bridge
  
  rabbitmq_net:
    driver: bridge
    name: rabbitmq_net